Livro venda
mgabrielacuenca/e-digi-pd pull request #6
Opened 2020-08-20 16:25 UTC by mgabrielacuenca

eu acho que eu poderia ter feito melhor

2020-08-20 19:03 UTC, wandersonmaceds requested changes

2020-08-20 19:03 UTC, wandersonmaceds commented on e-digi/src/dao/DaoCategoria.java
> +        if (categoriaSet.contains(categoria)) {
Não entendi, a lógica é quase a mesma, o add é mais direto, por que trocar?

2020-08-20 19:03 UTC, wandersonmaceds commented on e-digi/src/dao/DaoCategoria.java
>      public void addCategoria(Categoria categoria) {
Vou pegar no Pé aqui, se sua classe é um DaoCategoria (normalmente é comum se escrever o contrário: CategoriaDao, fica até mais semântico), por que seus métodos teriam o sufixo Categoria? Posso usar o DAO de categoria para salvar um Livro? Aqui ainda, a ideia é salvar a categoria ou adicionar ela em alguma coisa?

2020-08-20 19:03 UTC, wandersonmaceds commented on e-digi/src/dao/DaoCategoria.java
> +    private static Set<Categoria> categoriaSet = new HashSet<>();
Por que mudou pra estático aqui?

2020-08-20 19:03 UTC, wandersonmaceds commented on e-digi/src/dao/VendaLivro.java
> +public class VendaLivro {
Precisa mesmo especificar que a venda é de um Livro? Se eu criar Disco, vai haver um VendaDisco?

2020-08-20 19:03 UTC, wandersonmaceds commented on e-digi/src/dao/VendaLivro.java
> +    private DaoLivro daolivro = new DaoLivro();
Acoplamento muito forte seu carrinho depender diretamente do DAO.

2020-08-20 19:03 UTC, wandersonmaceds commented on e-digi/src/dao/VendaLivro.java
> +
Aqui acredito que você possa fazer de uma forma melhor. 
Se a gente pensar que o carrinho agrupa produtos e quantidades (map) que possuem uma certa lógica (sub-total), poderíamos criar nosso próprio "map", que encapsula essa lógica e seguir com isso 

ou...

Isolar a lógica que calcula o sub-total e reduzir esse sub-total em um total final.

2020-08-27 17:25 UTC, mgabrielacuenca commented on e-digi/src/dao/DaoCategoria.java
> +    private static Set<Categoria> categoriaSet = new HashSet<>();
eu tinha mudado pq ia fazer a venda do livro de outra forma, e no fim so precisava mudar o livro pra estatico, vou voltar como tava.

2020-08-27 17:40 UTC, mgabrielacuenca commented on e-digi/src/dao/DaoCategoria.java
> +        if (categoriaSet.contains(categoria)) {
eu queria tirar os sysout do dao e a unica forma que achei foi essa, isso eh ruim?

2020-08-29 00:32 UTC, mgabrielacuenca commented on e-digi/src/dao/VendaLivro.java
> +    private DaoLivro daolivro = new DaoLivro();
nesse caso ai eu nao vi como fazer de outra forma de fazer, qual seria a ideia?

2020-08-29 00:35 UTC, mgabrielacuenca commented on e-digi/src/dao/VendaLivro.java
> +
ajustei, acho que agora resolve..

2020-08-29 17:16 UTC, wandersonmaceds commented on e-digi/src/dao/VendaLivro.java
> +    private DaoLivro daolivro = new DaoLivro();
A ideia é que o responsável não precisa buscar quais produtos vai estar no pacote, mas sim, já receber os itens que já foram buscados. 

Pensa no mercantil, você não chega no caixa e pede pra pessoa ir buscar seus produtos, ele só registra os itens da compra e te cobra, a ideia é a mesma.

2020-08-29 17:17 UTC, wandersonmaceds commented on e-digi/src/dao/DaoCategoria.java
> +        if (categoriaSet.contains(categoria)) {
Se a ideia é tirar os prints de dentro do DAO, você pode retornar o booelan da operação do add. Então fora do DAO pode ter um if (true) print("salvo com sucesso") algo assim.

2020-08-29 17:29 UTC, wandersonmaceds approved these changes

2020-08-29 17:29 UTC, wandersonmaceds commented on e-digi/src/model/CarrinhoCompras.java
>          }
Se você precisa gerar uma string de saída com base em várias informações, sai mais barato usar uma estratégia diferente, primeiro criar toda a string em memória para depois imprimir de uma vez só. 

Dá uma olhada na StringBuilder.

Acredito que esse if possa ser simplificado, veja, se não tem produtos, você já pode lançar o erro. Você ainda vai precisa do if, mas pode descartar o else totalmente. Simplificando a leitura.  Além de que, lógicas se evitarmos o uso da negação, teremos um código mais simples de ler.

2020-08-29 17:29 UTC, wandersonmaceds commented on e-digi/src/model/CarrinhoCompras.java
> +    public void addLivroCarrinho(Livro livro, int qtdLivro) {
Sobre nomenclaturas, aqui tem dois pontos: o parametro já diz o tipo de objeto que precisa ser passado, então poderia remover o Livro do nome do método, se a classe já diz que é um carrinho de compras, então, o sufixo Carrinho também pode ser removido.

2020-08-29 17:29 UTC, wandersonmaceds commented on e-digi/src/model/CarrinhoCompras.java
> +        return sum;
Boa, Mandou bem! Aqui poderia dar return direto na expressão.

2020-09-07 12:24 UTC, wandersonmaceds requested changes

2020-09-07 12:24 UTC, wandersonmaceds commented on e-digi/src/dao/CategoriaDao.java
> +        categoriaSet.add(categoria);
o add do set retorna um boleano, ele já vai ver se o objeto que está sendo adicionado não está sendo replicado baseado no equals e hashcode do objeto,  Acredito que internamente ele já use o contains para inserir ou não o objeto, o que faz o método ser executado duas vezes. 

Tem outros sets que você faz a mesma coisa, sugiro usar o resultado do add para jogar ou não a exception.

2020-12-10 13:07 UTC, merged